### ISSUE TITLE
Subtitles unavailable

### ISSUE THREAD

**Issue by Stiruam14** [prof-membrane/plugin.video.ardmediathek_de#9]
When the old plugin still worked, enabling (coloured) subtitles helped me greatly with understanding what was going on in Tatort (I am Dutch, my German is far from perfect).

The new version doesn't have a setting for enabling subtitles. Can this be fixed or is the ARD API not allowing this anymore?

**Comment by prof-membrane** [comment]
I had to disable the function while moving to the JSON API of the ARD. It is still on my todo list.

You could use the add-ons of Das Erste, MDR and WDR in the meantime. All of them support coloured subtitles.

**Comment by prof-membrane** [comment]
Just a small status update: all coding is now on hold due to the eminent Krypton release.

BTW: Do you want to translate all generic strings to Dutch? 

All you need to do is to translate https://github.com/prof-membrane/script.module.libmediathek3/blob/master/resources/language/German/strings.po. Make a pull request or post it via pastebin.

**Comment by Stiruam14** [comment]
Thanks for the support! I'll translate the strings to Dutch somewhere this week.
